# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow
import sys
from icecream import ic

from Data import *
from Classes import *
from MarketMechanics import *
from ProductionMechanics import *
from economic_simulation import *


class Ui_MainWindow(object):
    def __init__(self):
        super(Ui_MainWindow, self).__init__()

    def setupUi(self, MainWindow):
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(12)

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(885, 904)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.tab = QtWidgets.QTabWidget(self.centralwidget)
        self.tab.setGeometry(QtCore.QRect(0, 0, 881, 871))
        self.tab.setObjectName("tab")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")

        self.label1_1 = QtWidgets.QLabel(self.tab1)
        self.label1_1.setGeometry(QtCore.QRect(20, 30, 71, 21))
        self.label1_1.setFont(font)
        self.label1_1.setObjectName("label1_1")

        self.label1_2 = QtWidgets.QLabel(self.tab1)
        self.label1_2.setGeometry(QtCore.QRect(110, 30, 81, 21))
        self.label1_2.setFont(font)
        self.label1_2.setObjectName("label1_2")

        self.tinput_quantity = QtWidgets.QLineEdit(self.tab1)
        self.tinput_quantity.setGeometry(QtCore.QRect(20, 60, 61, 20))
        self.tinput_quantity.setObjectName("tinput_quantity")

        self.tinput_profession = QtWidgets.QLineEdit(self.tab1)
        self.tinput_profession.setGeometry(QtCore.QRect(110, 60, 81, 21))
        self.tinput_profession.setObjectName("tinput_profession")

        self.b_Create_Citizen = QtWidgets.QPushButton(self.tab1)
        self.b_Create_Citizen.setGeometry(QtCore.QRect(210, 30, 161, 51))
        self.b_Create_Citizen.setFont(font)
        self.b_Create_Citizen.setObjectName("b_Create_Citizen")
        self.b_Create_Citizen.clicked.connect(self.create_citizen)



        self.txt_monitor = QtWidgets.QTextBrowser(self.tab1)
        self.txt_monitor.setGeometry(QtCore.QRect(30, 120, 821, 601))
        self.txt_monitor.setObjectName("txt_monitor")
        

        self.b_Update_Information = QtWidgets.QPushButton(self.tab1)
        self.b_Update_Information.setGeometry(QtCore.QRect(70, 760, 381, 41))
        self.b_Update_Information.setFont(font)
        self.b_Update_Information.setObjectName("b_Update_Information")
        self.b_Update_Information.clicked.connect(self.display)

        self.comboBox = QtWidgets.QComboBox(self.tab1)
        self.comboBox.setGeometry(QtCore.QRect(450, 760, 261, 41))
        self.comboBox.setFont(font)
        self.comboBox.setEditable(False)
        self.comboBox.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.comboBox.setMinimumContentsLength(0)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        
        self.tab.addTab(self.tab1, "")

        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tab.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 885, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tab.setCurrentIndex(0)
        self.comboBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.b_Create_Citizen.setText(_translate("MainWindow", "Create Citizen"))

        self.label1_1.setText(_translate("MainWindow", "Quantity:"))
        self.label1_2.setText(_translate("MainWindow", "Profession:"))

        self.b_Update_Information.setText(_translate("MainWindow", "Update Information"))

        self.comboBox.setCurrentText(_translate("MainWindow", "                             All"))
        self.comboBox.setItemText(0, _translate("MainWindow", "                             All"))
        self.comboBox.setItemText(1, _translate("MainWindow", "         Pops Commodities"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Current state of the marketplace"))

        self.tab.setTabText(self.tab.indexOf(self.tab1), _translate("MainWindow", "Tab 1"))
        self.tab.setTabText(self.tab.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))

    def create_citizen(self):
        if self.tinput_quantity.text() == '':
            createCitizens()
        elif self.tinput_quantity.text() or self.tinput_profession.text():
            createCitizens(self.tinput_quantity.text(), self.tinput_profession.text())

    def display(self, result):
        result = display_current_info_in_ui()
        self.txt_monitor.setText(result)
        

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
